import os.path

def parse_obj(filename):
    vertices = []
    print(f"// WARNING: this file was generated by mzr_build_mesg.py from '{filename}'")
    print("#pragma once")
    print("#include \"mzapo_renderer.h\"")
    print()
    print("")
    with open(filename, 'r') as f:
        lines = f.readlines()
        print("float vertices[] = {")
        for line in lines:
            if line.startswith('v '):
                # Parse vertex: v x y z
                parts = line.strip().split()
                x, y, z = map(float, parts[1:4])
                vertices.append((x, y, z))
        print("};")

        print("int indices[] = {")
        for line in lines:
            if line.startswith('f '):
                # Parse face: f i1 i2 i3 (only triangles, no texture/normal)
                parts = line.strip().split()
                indices = [int(p.split('/')[0]) for p in parts[1:4]]
                triangle = [vertices[i - 1] for i in indices]  # OBJ is 1-based
                print("\t", end="")
                for vert in triangle:
                    vert = [vert[0] * 2, 2 * vert[1], 2 *  vert[2]]
                    for v in vert:
                        v = round(1000.0 * v) / 1000.0
                        print(f"{v}, ", end="")
                    print("\t", end="")
                print("")
        print("};")

    # print("mzr_mesh_t ")

    print("};")

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python mzr_build.py <file.obj>")
    else:
        parse_obj(sys.argv[1])